### ISSUE TITLE
Can we find the teacher_weights somewhere?

### ISSUE THREAD

**Issue by Luodian** [Jia-Research-Lab/ReviewKD#8]
When I run your scripts "reviewKD.sh" and "baseline.sh" in Cifar100. There's FileNotFoundError: 
```bash
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cifar100_wrn-40-2__baseline1_best.pt'
Namespace(T=4.0, batch_size=128, ce_loss_weight=1.0, dataset='cifar100', epochs=240, gamma=0.1, kd_loss_weight=5.0, kd_warm_up=20.0, kl_loss_weight=1.0, lr=0.1, lr_adjust_step=[150, 180, 210], model='wrn-40-1', resume='', seed=148, suffix='reviewkd1', teacher='wrn-40-2', teacher_weight='checkpoints/cifar100_wrn-40-2__baseline1_best.pt', test=False, use_kl=False, wd=0.0005)
```

Where could I find those weights or can you release the related teacher weights so that we can download and better configure our experiment environment.

**Comment by akuxcw** [comment]
Hi, we didn't provide pretrained teachers for cifar-100 now. Because it's easy and fast to train a teacher by yourself. You can train the wrn-40-2 teacher using [this command](https://github.com/dvlab-research/ReviewKD/blob/master/CIFAR-100/script/baseline.sh#L5). If you find any problem to train the teacher. We will consider uploading the teacher weights.

**Comment by Luodian** [comment]
```bash
Files already downloaded and verified
Files already downloaded and verified
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    torch.save(cnn.state_dict(), 'checkpoints/' + test_id + '_best.pt')
  File "/anaconda/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/anaconda/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/anaconda/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cifar100_wrn-16-2__baseline1_best.pt
```
I think the problem still exists when running "baseline.sh".

**Comment by Luodian** [comment]
Thanks!

**Comment by akuxcw** [comment]
You need to make sure there is a "./checkpoints/" directory, using "mkdir checkpoints" to create one.
